# Generated by Django 2.2.7 on 2019-11-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('inventoryid', models.AutoField(primary_key=True, serialize=False)),
                ('partname', models.CharField(max_length=100)),
                ('numberofstocks', models.IntegerField()),
                ('parlevel', models.IntegerField()),
            ],
            options={
                'db_table': 'tblMasterInventory',
            },
        ),
    ]
