# Generated by Django 2.2.6 on 2019-11-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=30)),
                ('contractstartdate', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tblSupplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('supplierinvoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('supplierinvoicenumber', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('hst', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'tblSupplierInvoice',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('supplierordernumber', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supplierid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.Supplier')),
            ],
            options={
                'db_table': 'tblSupplierOrder',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory')),
                ('supplierordernumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierOrder')),
            ],
            options={
                'db_table': 'jncSupplierOrderLineItem',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityshipped', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory')),
                ('supplierinvoicenumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierInvoice')),
            ],
            options={
                'db_table': 'jncSupplierInvoiceLineItem',
            },
        ),
    ]
