# Generated by Django 2.2.7 on 2019-11-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('modeltypeid', models.AutoField(primary_key=True, serialize=False)),
                ('modeltypename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblkModelType',
            },
        ),
        migrations.CreateModel(
            name='PartInventory',
            fields=[
                ('partid', models.AutoField(primary_key=True, serialize=False)),
                ('inventoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterInventory.MasterInventory')),
            ],
            options={
                'db_table': 'jncPartInventory',
            },
        ),
        migrations.CreateModel(
            name='SubassemblyInventory',
            fields=[
                ('subassemblyid', models.AutoField(primary_key=True, serialize=False)),
                ('inventoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterInventory.MasterInventory')),
            ],
            options={
                'db_table': 'jncSubassemblyInventory',
            },
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('modelid', models.AutoField(primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=100)),
                ('modeltype', models.ForeignKey(on_delete=models.SET('Discontinued'), to='bike.ModelType')),
            ],
            options={
                'db_table': 'tblModel',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bikeid', models.AutoField(primary_key=True, serialize=False)),
                ('modelid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.BikeModel')),
            ],
            options={
                'db_table': 'tblBike',
            },
        ),
        migrations.CreateModel(
            name='SubassemblyPartsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('partid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.PartInventory')),
                ('subassemblyid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.SubassemblyInventory')),
            ],
            options={
                'db_table': 'tblSubassemblyPartsList',
                'unique_together': {('subassemblyid', 'partid')},
            },
        ),
        migrations.CreateModel(
            name='Subassembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('modelid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.BikeModel')),
                ('subassemblyid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.SubassemblyInventory')),
            ],
            options={
                'db_table': 'jncModelSubassembly',
                'unique_together': {('modelid', 'subassemblyid')},
            },
        ),
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.BikeModel')),
                ('partid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.PartInventory')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'tblPartList',
                'unique_together': {('modelid', 'partid')},
            },
        ),
    ]
