# Generated by Django 2.2.6 on 2019-11-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partlist',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='modeltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.ModelType'),
        ),
    ]
