# Generated by Django 2.2.6 on 2019-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20191129_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='partlist',
            name='partlist_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
