# Generated by Django 2.2.7 on 2019-11-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeltype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeid', models.IntegerField()),
                ('bikeid', models.IntegerField()),
                ('custoemrorderid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=100)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modeltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskschedule.ModelType')),
            ],
        ),
    ]
