# Generated by Django 2.2.7 on 2019-12-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskschedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='t_taskassigneddate',
            new_name='t_taskcreated',
        ),
    ]
